### ISSUE TITLE
Update deploy script to upload changes in config sets to solr cloud.

### ISSUE THREAD

**Issue by tampakis** [pulibrary/pul_solr#104]
Proposal: capistrano should

1. deploy to the solr boxes as it currently does
1. for each collection:
   1. remotely execute the command here on any one of the solr boxes https://github.com/pulibrary/pul-the-hard-way/issues/34#issuecomment-427481269
   1. reload each of the collections (https://lucene.apache.org/solr/guide/6_6/collections-api.html#CollectionsAPI-reload)

**Comment by hackmastera** [comment]
this is blocked by https://github.com/pulibrary/pul_solr/issues/111 to the extent that we need to know the mappings between these config directories and the collection names. Also, it will be easier to code if we align those directory names with collections.
