### ISSUE TITLE
Automate updating aliases

### ISSUE THREAD

**Issue by tampakis** [pulibrary/pul_solr#105]
http://localhost:9000/solr/admin/collections?action=CLUSTERSTATUS 
catalog-production is for the live version of the catalog index
catalog-rebuild is for the collection we use to reindex the catalog

**Comment by hackmastera** [comment]
This is now documented under "Swap in the new index" on our google doc https://docs.google.com/document/d/1bHvgfgyUmDXV7ROqEZFaRxJFEYhSSUbeQoQT883GMWg/edit#heading=h.c857gz643qtx

changing title to just "automated"

**Comment by tampakis** [comment]
Step 1: get the cluster status
Step 2: create an alias where the collection that is currently at catalog-rebuild becomes catalog-production and vice versa

**Comment by hackmastera** [comment]
there's also a list aliases command, as an alternative to cluster status. it's a bit more concise.
