### ISSUE TITLE
Rename catalog production collections

### ISSUE THREAD

**Issue by tampakis** [pulibrary/pul_solr#106]
Since both of the catalog collections can be the production one let's call them:
catalog-production1
catalog-production2

**Comment by tampakis** [comment]
catalog-production1 needs to be the "live" catalog collection first so that we can delete "catalog-reindex" and create a new catalog collection called "catalog-production2"

**Comment by hackmastera** [comment]
once this is done ensure https://docs.google.com/document/d/1bHvgfgyUmDXV7ROqEZFaRxJFEYhSSUbeQoQT883GMWg/edit#heading=h.19qtl9pnejo1 is up to date.

**Comment by eliotjordan** [comment]
@tampakis I'm pretty sure this can be closed. Agree?
