### ISSUE TITLE
rename subdirectories of solr_configs to match their collection names

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pul_solr#111]
dpul-blacklight -> dpul-production
figgy
lae-blacklight -> lae
orangelight -> catalog-production (would be deployed to catalog-production1 and/or catalog-production2)
orangelight_staging -> catalog-staging
pulmap

**Comment by hackmastera** [comment]
do we currently deploy `dpul-blacklight` to both dpul-production and dpul-staging?

**Comment by hackmastera** [comment]
there are also `lae-blacklight-staging` and `pulmap-staging` cores in solrcloud.

**Comment by christinach** [comment]
Do we want to update the name in core.properties as well? I don't think it matters for solr cloud though. @tampakis ?
