### ISSUE TITLE
catalog-production1 is using wrong configset

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pul_solr#170]
It should use `catalog-production` but it is using a configset called `orangelight` which does not exist in this repo.

I believe the `orangelight` configset should be deleted. I think also the `catalog-production1` and `catalog-production2` configsets should be deleted, as both the collections they should all be using the `catalog-production` configset.

I believe this means we have to delete the `catalog-production1` collection and re-create it. It doesn't look like there's a way to point it at a different configset.

For now the catalog-production files have been deployed to all 4 of these configsets.

**Comment by hackmastera** [comment]
oh it looks like we may be able to use https://lucene.apache.org/solr/guide/7_7/command-line-utilities.html#link-a-collection-to-a-configset to change the configset used by the collection.

**Comment by hackmastera** [comment]
Another one: cicognara is using a config set called `cicognara-config`, but this repo expects it to be using `cicognara`.

**Comment by tampakis** [comment]
Yeah I think the stale config set names were before we had set up the deploy scripts to update and reload the configsets. Glad it seems like we won't need to recreate the collections

**Comment by hackmastera** [comment]
All apps using `orangelight` config set should be moved to `catalog-production` or `catalog-staging`, as appropriate. this includes `reserves` and `dss`.

**Comment by hackmastera** [comment]
These are all resolved. I also deleted a bunch of the config sets so they won't confuse us by being there.
