### ISSUE TITLE
Fix CJK tokenization beyond stop-gap

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pul_solr#188]
Currently we've disabled bigrams for CJK queries, which we expect will decrease the quality of the keyword match retrieval behavior.

https://github.com/pulibrary/pul_solr/issues/187 might help.

Discussion on blacklight slack channel suggests that upgrading to solr 8.1 would mitigate the bug; however the queries that previously caused the crash would fail.

To patch the bug without upgrading solr we could use https://issues.apache.org/jira/browse/SOLR-13336. Note M. Gibney endorses a different patch, but using it would mean departing from solr core longer-term:

"I would expect that patch (the one officially applied for 8.1+) to still generate pretty heavy queries, and for individual queries to continue to fail ... albeit without crashing your entire index :slightly_smiling_face:. I'm curious what your experience has been.
FWIW, we're running a different patch, which basically reverts https://issues.apache.org/jira/browse/LUCENE-8531, avoiding the exponential query expansion issue altogether (at the expense of somewhat inconsistent proximity query scoring, I guess?)"

**Comment by tpendragon** [comment]
`고려의 후삼국 통일과 후백제` should return a record with the title `고려의후삼국통일과후백제`
