### ISSUE TITLE
Analyze heap dumps from 2020-01-24

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pul_solr#190]
New heap dumps from crash event are in deploy directory on both lib-solr1 and lib-solr3.

Someone with more gigs of memory than me will have to do it :(

**Comment by tpendragon** [comment]
I can look into this on Monday. Right now my theory is it's the WordDelimiterGraphFilter, and the query that's problematic is in #solr.

**Comment by hackmastera** [comment]
We found the queries and figured out what led to the crash without using the heap dumps; closing this.
