### ISSUE TITLE
Ensure each collection has at least 2 replicas

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/pul_solr#199]
To improve resilience to downtime

The following currently have only 1:

- [x] dss-production1
- [x] pdc-discovery-production
- [x] pulmap
- [x] special-collections-prod1

**Comment by carolyncole** [comment]
Looks like this is still an issue for dss and special-collections

**Comment by carolyncole** [comment]
dss-prod1 & special-collections-prod1 were deleted infavaor of dss-prod2 and special-collections-prod2, which have a replication factor of 2

**Comment by hackartisan** [comment]
The replicationfactor can be updated from the box with a curl command like, e.g.:
`curl "http://localhost:8983/solr/admin/collections?action=MODIFYCOLLECTION&collection=pulmap&replicationFactor=2"`

Then another replica added like, e.g.:
`curl "http://localhost:8983/solr/admin/collections?action=ADDREPLICA&collection=pulmap&shard=shard1"`

**Comment by hectorcorrea** [comment]
Executed the same commands that @hackartisan posted above but for `pdc-discovery-production`
