### ISSUE TITLE
Schedule migrated collections for deletion from solr 7 clouds

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pul_solr#223]
catalog-staging
catalog-production[n]
catalog-test
catalog-production-backup
reserves
dss-staging
dss-production

**Comment by christinach** [comment]
Thank you for listing the collections @hackmastera. The catalog-test should not be deleted the data quality group may need more time to review. I will ask them.

**Comment by hackmastera** [comment]
This was done April 6th
