### ISSUE TITLE
Branch migration master -> main

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pul_solr#238]
Note that other applications reference the master branch to pull in configs: e.g. https://github.com/pulibrary/orangelight/issues/2309

**Comment by jrgriffiniii** [comment]
This has been updated, I will proceed with evaluating other repositories which are affected by this.

**Comment by hackartisan** [comment]
@jrgriffiniii What steps did you take here? I'm noticing that the open PRs are still based against `master`

**Comment by hackartisan** [comment]
I think I got the last couple of rake tasks. I re-based one PR and the other one looked like it needed a rebase anyway so I left it for now since there's no chance of merging it accidentally.
