### ISSUE TITLE
Create a catalog-qa index in solr8cloud_staging

### ISSUE THREAD

**Issue by christinach** [pulibrary/pul_solr#276]
The `catalog-qa` index was deleted from `solr8cloud_staging`. 
Temporarily I pointed https://catalog-qa.princeton.edu/ to catalog-staging index without changing ansible. 
It is preferred to have a `catalog-qa` index in `solr8cloud_staging`. We initially created this index for demos.

**Comment by christinach** [comment]
If it is a problem having one because of the storage, then we should update ansible to point https://catalog-qa.princeton.edu/ to the `catalog-staging` index.

**Comment by carolyncole** [comment]
fixed by: https://github.com/pulibrary/pul_solr/pull/310
