### ISSUE TITLE
Delete catalog-production configset

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pul_solr#277]
It's been replaced by catalog-production-v2. See ADR: https://github.com/pulibrary/pul_solr/blob/main/architecture-decisions/0005-catalog-configset-rotation.md

Blocked until after alma go-live.

**Comment by christinach** [comment]
The catalog-production configset  is used by the DSS app.

**Comment by carolyncole** [comment]
Blocked by #258

**Comment by hackartisan** [comment]
close in favor of #258
