### ISSUE TITLE
Catalog: Include uncontrolled_keyword_unstem_search in keyword search results

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/pul_solr#361]
### Success criteria

- [x] The `uncontrolled_keyword_unstem_search` solr field is consulted for keyword searches
- [x] The `uncontrolled_keyword_unstem_search` solr field is not consulted for subject searches

See e765f7f21d46b407f059babcc63d726885e0f3d5 for an example (although it also adds to the subject searches, which we do not want to do for this ticket)

**Comment by maxkadel** [comment]
In order to perform correctly this may need to be changed to an `*_unstem_search` dynamic field
