### ISSUE TITLE
migrate from lib-solr8 to lib-solr8-d staging

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/pul_solr#395]
The following collections need to be migrated to the new bionic cluster. These can either be re-indexed from scratch and/or restored from backup. 

- [x] catalog-qa1
- [x] catalog-qa2
- [x] catalog-staging1
- [x] catalog-staging2
- [ ] cdh_geniza
- [ ] cdh_ppa
- [ ] cdh_shxco
- [ ] cicognara-staging
- [ ] cicognara-test
- [ ] dpul-production
- [ ] dpul-staging
- [ ] figgy-staging
- [ ] geniza
- [ ] lae-staging1
- [ ] lae-staging2
- [ ] library-staging1
- [ ] oawaiver-staging
- [ ] pdc-discovery-staging-1
- [ ] pdc-discovery-staging-2
- [ ] pulfalight-qa-1
- [ ] pulmap-staging
- [ ] special-collections-staging1

**Comment by hackartisan** [comment]
close in favor of pulibrary/princeton_ansible#4666 -- we don't need both of these
